# Generated by Django 3.1.3 on 2021-05-23 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('resume_link', models.URLField(blank=True, max_length=100, null=True)),
                ('image_file', models.ImageField(blank=True, default='create.jpg', upload_to='users/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Open to work', 'Open to work'), ('Working', 'Working')], default='Working', max_length=30)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
